#!/bin/bash
# codesearch-docker.sh — Docker container lifecycle for codesearch.
# Called from the VS Code extension via: wsl.exe bash -l <this_script> <cmd> [options]
#
# Commands: setup | start | stop | restart | build | register-mcp
#
# Options:
#   --config <wsl-path>     Path to config.json generated by the extension (required)
#   --container <name>      Docker container name       (default: codesearch)
#   --image <name>          Docker image name           (default: codesearch-mcp)
#   --mcp-port <port>       MCP SSE port                (default: 3000)
#   --data-vol <name>       Docker data volume name     (default: codesearch_data)
#   --repo-path <wsl-path>  Repo root — required for build/setup

set -euo pipefail

CMD="${1:-help}"
shift 2>/dev/null || true

CONFIG_PATH=""
CONTAINER="codesearch"
IMAGE="codesearch-mcp"
MCP_PORT=3000
DATA_VOL="codesearch_data"
REPO_PATH=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config)    CONFIG_PATH="$2"; shift 2 ;;
        --container) CONTAINER="$2";   shift 2 ;;
        --image)     IMAGE="$2";       shift 2 ;;
        --mcp-port)  MCP_PORT="$2";    shift 2 ;;
        --data-vol)  DATA_VOL="$2";    shift 2 ;;
        --repo-path) REPO_PATH="$2";   shift 2 ;;
        *) echo "[docker] Unknown option: $1" >&2; exit 1 ;;
    esac
done

log() { echo "[docker] $*"; }
die() { echo "[docker] ERROR: $*" >&2; exit 1; }

require_config() {
    [ -n "$CONFIG_PATH" ] || die "--config is required"
    [ -f "$CONFIG_PATH" ] || die "config.json not found: $CONFIG_PATH"
}

# Parse api_key, Typesense port, and derived API port from config.json.
read_config() {
    require_config
    API_KEY=$(python3 -c "import json; d=json.load(open('$CONFIG_PATH')); print(d.get('api_key',''))")
    TS_PORT=$(python3 -c "import json; d=json.load(open('$CONFIG_PATH')); print(d.get('port', 8108))")
    API_PORT=$((TS_PORT + 1))
}

do_stop() {
    log "Stopping container '$CONTAINER'..."
    docker stop "$CONTAINER" 2>/dev/null || true
    docker rm   "$CONTAINER" 2>/dev/null || true
    log "Done."
}

do_build() {
    [ -n "$REPO_PATH" ] || die "--repo-path required to build the image"
    local dockerfile="$REPO_PATH/docker/Dockerfile"
    [ -f "$dockerfile" ] || die "Dockerfile not found: $dockerfile"
    log "Building image '$IMAGE' (this may take a few minutes)..."
    docker build -t "$IMAGE" -f "$dockerfile" "$REPO_PATH"
    log "Image built."
}

do_start() {
    read_config
    log "Starting container '$CONTAINER'..."

    # Build docker run arg array (avoids eval and handles paths with spaces).
    local -a ARGS
    ARGS=(
        run -d
        --name "$CONTAINER"
        -p "${MCP_PORT}:3000"
        -p "${TS_PORT}:8108"
        -p "${API_PORT}:8109"
        -e "CODESEARCH_API_HOST=0.0.0.0"
        -v "${CONFIG_PATH}:/app/codesearch/config.json:ro"
        -v "${DATA_VOL}:/typesensedata"
    )

    # One volume mount per root from config.json (Windows paths → forward-slash Linux paths).
    while IFS=$'\t' read -r name win_path; do
        local lpath="${win_path//\\//}"
        lpath="${lpath%/}"
        ARGS+=(-v "${lpath}:/source/${name}:ro")
    done < <(python3 -c "
import json
with open('$CONFIG_PATH') as f:
    d = json.load(f)
# _mounts holds host-side WSL paths; roots holds container-internal paths
for name, path in d.get('_mounts', d.get('roots', {})).items():
    print(name + '\t' + path)
")

    ARGS+=("$IMAGE")
    docker "${ARGS[@]}"
    log "Container started — streaming logs until ready..."

    # Stream container logs, printing each line, until the MCP server signals ready.
    # "Uvicorn running" is the last line printed by entrypoint.sh before it is ready.
    local ready=0
    while IFS= read -r line; do
        echo "$line"
        if [[ "$line" == *"Uvicorn running"* || "$line" == *"Ready for connections"* ]]; then
            ready=1
            break
        fi
    done < <(timeout 300 docker logs -f "$CONTAINER" 2>&1)

    if [ $ready -eq 1 ]; then
        log "Server is ready."
    else
        log "WARNING: Server did not reach ready state within 5 min — check 'docker logs ${CONTAINER}'."
    fi
}

do_register_mcp() {
    local url="http://localhost:${MCP_PORT}/sse"
    log "Registering MCP at $url..."
    claude mcp remove --scope user tscodesearch 2>/dev/null || true
    claude mcp add --scope user --transport sse tscodesearch "$url"
    log "MCP registered."
}

do_setup() {
    log "=== Code Search Docker Setup ==="
    read_config

    docker info --format '{{.ID}}' >/dev/null 2>&1 \
        || die "Docker is not running. Start Docker Desktop and try again."
    log "Docker is running."

    if ! docker images -q "$IMAGE" 2>/dev/null | grep -q .; then
        [ -n "$REPO_PATH" ] || die "--repo-path required to build the image"
        do_build
    else
        log "Image '$IMAGE' already exists — skipping build."
    fi

    do_stop
    do_start

    if do_register_mcp 2>/dev/null; then
        :
    else
        log "WARNING: MCP registration failed (is 'claude' in PATH?)."
        log "  Run manually: claude mcp add --scope user --transport sse tscodesearch http://localhost:${MCP_PORT}/sse"
    fi

    log "=== Setup complete ==="
}

case "$CMD" in
    build)        do_build ;;
    start)        do_start ;;
    stop)         do_stop ;;
    restart)      do_stop; do_start ;;
    setup)        do_setup ;;
    register-mcp) read_config; do_register_mcp ;;
    *) echo "Usage: codesearch-docker.sh {setup|start|stop|restart|build|register-mcp} [options]" >&2; exit 1 ;;
esac
