#!/bin/bash
# codesearch-wsl.sh — WSL indexserver lifecycle for codesearch.
# Called from the VS Code extension via: wsl.exe bash -l <this_script> <cmd> [options]
#
# Commands: setup | setup-venvs | start | stop | restart | register-mcp
#
# Options:
#   --config <wsl-path>     Path to config.json generated by the extension (required for start)
#   --repo-path <wsl-path>  Path to the tscodesearch repo root (required)
#   --mcp-port <port>       MCP port (default: 3000)

set -euo pipefail

CMD="${1:-help}"
shift 2>/dev/null || true

CONFIG_PATH=""
REPO_PATH=""
MCP_PORT=3000

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config)    CONFIG_PATH="$2"; shift 2 ;;
        --repo-path) REPO_PATH="$2";   shift 2 ;;
        --mcp-port)  MCP_PORT="$2";    shift 2 ;;
        *) echo "[wsl] Unknown option: $1" >&2; exit 1 ;;
    esac
done

log() { echo "[wsl] $*"; }
die() { echo "[wsl] ERROR: $*" >&2; exit 1; }

require_repo() {
    [ -n "$REPO_PATH" ] || die "--repo-path is required"
    [ -d "$REPO_PATH" ] || die "Repo path not found: $REPO_PATH"
}

# Ensure config.json is present in the repo root where config.py reads it.
# In WSL mode the extension writes config.json directly to the repo root, so
# this is normally a no-op.  The --config path is still accepted as a fallback
# (e.g. first-time setup before repoPath is fully resolved).
sync_config() {
    require_repo
    local dest="$REPO_PATH/config.json"
    if [ -f "$dest" ]; then
        log "Config already at $dest"
        return
    fi
    # Fallback: copy from extension storage path if provided.
    [ -n "$CONFIG_PATH" ] || die "config.json not found at $dest and --config not provided"
    [ -f "$CONFIG_PATH" ] || die "config.json not found: $CONFIG_PATH"
    cp "$CONFIG_PATH" "$dest"
    log "Config copied to $dest"
}

install_node() {
    require_repo

    # Source nvm if already installed but not in PATH
    NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
    # shellcheck source=/dev/null
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

    if command -v node >/dev/null 2>&1; then
        log "Node.js already installed: $(node --version)"
    else
        log "Installing nvm..."
        curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        # shellcheck source=/dev/null
        . "$NVM_DIR/nvm.sh"
        log "Installing Node.js 20 LTS..."
        nvm install 20
        nvm alias default 20
        log "Node.js installed: $(node --version)"
    fi

    # Install VS Code extension test dependencies into WSL home (not /mnt/)
    VSCODE_DIR="$REPO_PATH/vscode-codesearch"
    VSCODE_DEPS="$HOME/.local/vscode-codesearch-deps"
    if [ -f "$VSCODE_DIR/package.json" ]; then
        log "Installing vscode-codesearch npm dependencies into $VSCODE_DEPS..."
        mkdir -p "$VSCODE_DEPS"
        cp "$VSCODE_DIR/package.json" "$VSCODE_DEPS/"
        [ -f "$VSCODE_DIR/package-lock.json" ] && cp "$VSCODE_DIR/package-lock.json" "$VSCODE_DEPS/"
        (cd "$VSCODE_DEPS" && npm ci --silent)
        log "npm dependencies ready."
    fi
}

install_venvs() {
    require_repo
    log "Checking Python version..."
    python3 -c 'import sys; assert sys.version_info >= (3,10), "Python 3.10+ required"' \
        || die "Python 3.10+ is required (found: $(python3 --version 2>&1))"
    log "Found: $(python3 --version 2>&1)"

    # MCP venv (~/.local/mcp-venv)
    if [ ! -f "$HOME/.local/mcp-venv/bin/python" ]; then
        log "Creating mcp-venv..."
        python3 -m venv "$HOME/.local/mcp-venv"
    fi
    log "Updating mcp-venv packages..."
    "$HOME/.local/mcp-venv/bin/pip" install --quiet --upgrade \
        mcp tree-sitter tree-sitter-c-sharp typesense

    # Indexserver venv (~/.local/indexserver-venv)
    if [ ! -f "$HOME/.local/indexserver-venv/bin/python" ]; then
        log "Creating indexserver-venv..."
        python3 -m venv "$HOME/.local/indexserver-venv"
    fi
    log "Updating indexserver-venv packages..."
    "$HOME/.local/indexserver-venv/bin/pip" install --quiet --upgrade \
        typesense tree-sitter tree-sitter-c-sharp tree-sitter-python watchdog pathspec

    install_node

    log "Venvs ready."
}

do_start() {
    sync_config
    require_repo
    log "Starting indexserver..."
    bash -l "$REPO_PATH/ts.sh" start
    log "Indexserver started."
}

do_stop() {
    require_repo
    log "Stopping indexserver..."
    bash -l "$REPO_PATH/ts.sh" stop 2>/dev/null || true
    log "Indexserver stopped."
}

do_register_mcp() {
    require_repo
    log "Registering MCP server..."
    claude mcp remove --scope user tscodesearch 2>/dev/null || true
    claude mcp add --scope user tscodesearch "$REPO_PATH/mcp.sh"
    log "MCP registered."
}

do_setup() {
    log "=== Code Search WSL Setup ==="
    install_venvs
    do_start

    if do_register_mcp 2>/dev/null; then
        :
    else
        log "WARNING: MCP registration failed (is 'claude' in PATH?)."
        log "  Run manually: claude mcp add --scope user tscodesearch $REPO_PATH/mcp.sh"
    fi

    log "=== Setup complete ==="
}

case "$CMD" in
    setup-venvs)  install_venvs ;;
    start)        do_start ;;
    stop)         do_stop ;;
    restart)      do_stop; do_start ;;
    setup)        do_setup ;;
    register-mcp) do_register_mcp ;;
    *) echo "Usage: codesearch-wsl.sh {setup|setup-venvs|start|stop|restart|register-mcp} [options]" >&2; exit 1 ;;
esac
